version: 2
run: 
  go: "1.24"
  timeout: 10m
  allow-parallel-runners: true
  concurrency: 4

linters:
  default: none
  enable:
    - errcheck
    - govet
    - gocyclo
    - gosec
    - unconvert
    - ineffassign
    - misspell
    - unused
  settings:
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - Infof
            - Warnf
            - Errorf
            - Fatalf

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  exclusions:
    paths:
      - build
      - client
      - docs
      - models
      - restapi
      - api

issues:
  uniq-by-line: true

formatters:
  enable:
    - gofmt
    - gci
    - goimports
  settings:
    gofmt:
      simplify: false

# output configuration options
output:
  formats: 
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
