# Build the manager binary
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25@sha256:c5d1bbc9c6ba9403017a30c2c71e9e28c9f43ffed2e60573a6de20e8ac753689 as builder

WORKDIR /workspace
COPY . .
# Build
RUN CGO_ENABLED=1 go build -a -o manager main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:457cb288730d29e2a59823b3b56341466fa94f3158e399c5ab2c4409fee0c562

ARG version=2.17

LABEL \
    name="multicluster-engine/cluster-api-provider-agent-rhel9" \
    cpe="cpe:/a:redhat:multicluster_engine:2.17::el9" \
    com.redhat.component="cluster-api-provider-agent" \
    description="Kubernetes-native declarative infrastructure for agent-based installation. \
    cluster-api-provider-agent serves as infrastructure provider for Kubernetes cluster-api." \
    io.k8s.description="Kubernetes-native declarative infrastructure for agent-based installation. \
    cluster-api-provider-agent serves as infrastructure provider for Kubernetes cluster-api." \
    summary="Kubernetes-native declarative infrastructure for agent-based installation." \
    io.k8s.display-name="cluster-api-provider-agent" \
    io.openshift.tags="mce hypershift cluster-api-provider-agent" \
    version="${version}" \
    release="${version}" \
    distribution-scope="public" \
    url="https://github.com/openshift/cluster-api-provider-agent" \
    vendor="Red Hat, Inc."

WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
